name: Build and Publish Docker Image

inputs:
  docker_registry:
    type: string
    required: true
    description: The Docker registry to push the image to
  docker_username:
    type: string
    required: true
    description: The username for the Docker registry
  docker_password:
    type: string
    required: true
    description: The password for the Docker registry
  backup_registry:
    type: string
    required: false
    description: The backup Docker registry to push the image to
  backup_username:
    type: string
    required: false
    description: The username for the backup Docker registry
  backup_password:
    type: string
    required: false
    description: The password for the backup Docker registry
  backup_remove_username:
    type: boolean
    required: false
    default: true
    description: Whether to remove the username when pushing to the backup registry

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Lowercase the repo name
      shell: bash
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Set backup condition
      shell: bash
      run: |
        if [[ "${{ inputs.backup_registry }}" != "" && "${{ inputs.backup_username }}" != "" && "${{ inputs.backup_password }}" != "" ]]; then
          echo "USE_BACKUP=true" >> $GITHUB_ENV
        else
          echo "USE_BACKUP=false" >> $GITHUB_ENV
        fi

    - name: Set backup repo name
      if: env.USE_BACKUP == 'true'
      shell: bash
      run: |
        if [[ "${{ inputs.backup_remove_username }}" == "true" ]]; then
          echo "BACKUP_REPO=$(echo $REPO | cut -d'/' -f2-)" >> $GITHUB_ENV
        else
          echo "BACKUP_REPO=$REPO" >> $GITHUB_ENV
        fi

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.docker_registry }}/${{ env.REPO }}
        tags: |
          type=raw,value=latest

    - name: Docker meta for backup registry
      if: env.USE_BACKUP == 'true'
      id: meta_backup
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.backup_registry }}/${{ env.BACKUP_REPO }}
        tags: |
          type=raw,value=latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Login to backup registry
      uses: docker/login-action@v2
      if: env.USE_BACKUP == 'true'
      with:
        registry: ${{ inputs.backup_registry }}
        username: ${{ inputs.backup_username }}
        password: ${{ inputs.backup_password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      id: docker_build
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Push to backup registry
      if: env.USE_BACKUP == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta_backup.outputs.tags }}
        labels: ${{ steps.meta_backup.outputs.labels }}
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        inputs: ${{ steps.docker_build.outputs.digest }}
